# This is a TOML document. Boom
[discovery]
    nodes = ["127.0.0.1:7171"]
    weight = 10
    region = "china"
    zone = "sh"
    host = "job"
    env = "dev"

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["10.6.1.1:9094"]
